import React from 'react';
import { motion } from 'framer-motion';
import { Shield, Users, Bell, HeadphonesIcon, BarChart3, Lock, Mail, AlertTriangle } from 'lucide-react';
import './PrivacyPolicy.css';

const PrivacyPolicy = () => {
  return (
    <div className="privacy-policy-container">
      {/* Hero Section */}
      <motion.section 
        className="privacy-hero"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <div className="privacy-hero-content">
          <h1 className="privacy-title">Privacy Policy</h1>
          <p className="privacy-subtitle">
            Your privacy is important to us. Learn how we collect, use, and protect your information.
          </p>
          <div className="last-updated">
            Last updated: September 15, 2025
          </div>
        </div>
      </motion.section>

      {/* Content Section */}
      <motion.div 
        className="privacy-content"
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.2 }}
      >
        <div className="content-wrapper">
          {/* Table of Contents */}
          <div className="table-of-contents">
            <h3>Quick Navigation</h3>
            <ul>
              <li><a href="#introduction">Introduction</a></li>
              <li><a href="#definitions">Definitions</a></li>
              <li><a href="#information-collection">Information Collection</a></li>
              <li><a href="#data-use">Use of Data</a></li>
              <li><a href="#data-retention">Data Retention</a></li>
              <li><a href="#data-transfer">Data Transfer</a></li>
              <li><a href="#data-disclosure">Data Disclosure</a></li>
              <li><a href="#data-security">Data Security</a></li>
              <li><a href="#your-rights">Your Rights</a></li>
              <li><a href="#contact">Contact Us</a></li>
            </ul>
          </div>

          {/* Main Content */}
          <div className="main-content">
            
            {/* Introduction */}
            <section id="introduction" className="content-section">
              <h2>Introduction</h2>
              <p>
                Welcome to <strong>Kanpan Organic Farms Private Limited</strong> ("us," "we," or "our") operating as 
                <a href="https://www.naturallygood.in/" target="_blank" rel="noopener noreferrer"> https://www.naturallygood.in/</a> 
                (hereinafter referred to as "Service").
              </p>
              <p>
                Our Privacy Policy governs your visit to https://www.naturallygood.in/ and explains how we collect, 
                safeguard and disclose information that results from your use of our Service.
              </p>
              <p>
                We use your data to provide and improve Service. By using Service, you agree to the collection and 
                use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, 
                the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
              </p>
              <p>
                Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy 
                constitutes your agreement with us ("agreement").
              </p>
            </section>

            {/* Definitions */}
            <section id="definitions" className="content-section">
              <h2>Definitions</h2>
              <div className="definitions-grid">
                <div className="definition-item">
                  <h4>SERVICE</h4>
                  <p>means the https://www.naturallygood.in/ website operated by Kanpan Organic Farms Private Limited.</p>
                </div>
                <div className="definition-item">
                  <h4>PERSONAL DATA</h4>
                  <p>means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                </div>
                <div className="definition-item">
                  <h4>USAGE DATA</h4>
                  <p>is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
                </div>
                <div className="definition-item">
                  <h4>COOKIES</h4>
                  <p>are small files stored on your device (computer or mobile device).</p>
                </div>
                <div className="definition-item">
                  <h4>DATA CONTROLLER</h4>
                  <p>means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.</p>
                </div>
                <div className="definition-item">
                  <h4>THE USER</h4>
                  <p>is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
                </div>
              </div>
            </section>

            {/* Information Collection */}
            <section id="information-collection" className="content-section">
              <h2>Information Collection and Use</h2>
              <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
              
              <h3>Types of Data Collected</h3>
              
              <div className="data-type-card">
                <h4>Personal Data</h4>
                <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include:</p>
                <ul>
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, Country, State, Province, Postal code, City</li>
                  <li>Cookies and Usage Data</li>
                </ul>
                <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you via multiple communication channels. You may opt out of receiving any, or all, of these communications from us by following the relevant unsubscribe link.</p>
              </div>

              <div className="data-type-card">
                <h4>Usage Data</h4>
                <p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device ("Usage Data").</p>
                <p>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
              </div>

              <div className="data-type-card">
                <h4>Location Data</h4>
                <p>We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service.</p>
                <p>You can enable or disable location services when you use our Service at any time by way of your device settings.</p>
              </div>

              <div className="data-type-card">
                <h4>Tracking Cookies Data</h4>
                <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
                <p>Examples of Cookies we use:</p>
                <ul>
                  <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
                  <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                  <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
                  <li><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
                </ul>
              </div>
            </section>

            {/* Use of Data */}
            <section id="data-use" className="content-section">
              <h2>Use of Data</h2>
              <p>We use the collected data for various purposes:</p>
              <div className="purposes-grid">
                <div className="purpose-item">
                  <div className="purpose-icon"><Shield size={32} color="#78B826" /></div>
                  <h4>Service Provision</h4>
                  <p>To provide and maintain our Service</p>
                </div>
                <div className="purpose-item">
                  <div className="purpose-icon"><Bell size={32} color="#78B826" /></div>
                  <h4>Notifications</h4>
                  <p>To notify you about changes to our Service</p>
                </div>
                <div className="purpose-item">
                  <div className="purpose-icon"><HeadphonesIcon size={32} color="#78B826" /></div>
                  <h4>Customer Support</h4>
                  <p>To provide customer support</p>
                </div>
                <div className="purpose-item">
                  <div className="purpose-icon"><BarChart3 size={32} color="#78B826" /></div>
                  <h4>Analytics</h4>
                  <p>To gather analysis or valuable information so that we can improve our Service</p>
                </div>
                <div className="purpose-item">
                  <div className="purpose-icon"><Lock size={32} color="#78B826" /></div>
                  <h4>Security</h4>
                  <p>To detect, prevent and address technical issues</p>
                </div>
                <div className="purpose-item">
                  <div className="purpose-icon"><Mail size={32} color="#78B826" /></div>
                  <h4>Communications</h4>
                  <p>To provide you with news, special offers and general information</p>
                </div>
              </div>
            </section>

            {/* Data Retention */}
            <section id="data-retention" className="content-section">
              <h2>Retention of Data</h2>
              <div className="retention-info">
                <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
                <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
              </div>
            </section>

            {/* Data Transfer */}
            <section id="data-transfer" className="content-section">
              <h2>Transfer of Data</h2>
              <div className="transfer-warning">
                <h4><AlertTriangle size={20} color="#dc2626" style={{display: 'inline', marginRight: '8px'}} />Important Notice</h4>
                <p>Your information, including Personal Data, may be transferred to, and maintained on, computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
                <p>If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.</p>
              </div>
            </section>

            {/* Data Security */}
            <section id="data-security" className="content-section">
              <h2>Security of Data</h2>
              <div className="security-info">
                <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
              </div>
            </section>

            {/* Your Rights */}
            <section id="your-rights" className="content-section">
              <h2>Your Data Protection Rights</h2>
              <div className="rights-grid">
                <div className="right-item">
                  <h4>Right to Access</h4>
                  <p>You have the right to access, update or delete the information we have on you</p>
                </div>
                <div className="right-item">
                  <h4>Right to Rectification</h4>
                  <p>You have the right to have your information rectified if that information is inaccurate or incomplete</p>
                </div>
                <div className="right-item">
                  <h4>Right to Object</h4>
                  <p>You have the right to object to our processing of your Personal Data</p>
                </div>
                <div className="right-item">
                  <h4>Right to Restriction</h4>
                  <p>You have the right to request that we restrict the processing of your personal information</p>
                </div>
                <div className="right-item">
                  <h4>Right to Data Portability</h4>
                  <p>You have the right to be provided with a copy of your Personal Data in a structured, machine-readable format</p>
                </div>
                <div className="right-item">
                  <h4>Right to Withdraw Consent</h4>
                  <p>You have the right to withdraw your consent at any time where we rely on your consent to process your personal information</p>
                </div>
              </div>
            </section>

            {/* Contact */}
            <section id="contact" className="content-section">
              <h2>Contact Us</h2>
              <div className="contact-card">
                <h4>Questions about this Privacy Policy?</h4>
                <p>If you have any questions about this Privacy Policy or Grievances, please contact us:</p>
                <div className="contact-info">
                  <div className="contact-item">
                    <span className="contact-label">Email:</span>
                    <a href="mailto:admin@naturallygood.in">admin@naturallygood.in</a>
                  </div>
                  <div className="contact-item">
                    <span className="contact-label">Company:</span>
                    <span>Kanpan Organic Farms Private Limited</span>
                  </div>
                  <div className="contact-item">
                    <span className="contact-label">Website:</span>
                    <a href="https://www.naturallygood.in/" target="_blank" rel="noopener noreferrer">www.naturallygood.in</a>
                  </div>
                </div>
              </div>
            </section>

          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default PrivacyPolicy;