import React from 'react';
import { motion } from 'framer-motion';
import SEOHead from '../components/SEO/SEOHead';
import { 
  FileText, 
  User, 
  CheckCircle, 
  UserPlus, 
  CreditCard, 
  Truck, 
  Info, 
  Shield, 
  AlertTriangle, 
  Scale, 
  Ban, 
  Users, 
  Copyright, 
  XCircle, 
  Eye, 
  MessageSquare 
} from 'lucide-react';
import './TermsConditions.css';

const TermsConditions = () => {
  return (
    <div className="terms-conditions-container">
      <SEOHead 
        title="Terms & Conditions - NaturallyGood | Service Agreement & Usage Policy"
        description="Read NaturallyGood's terms and conditions for using our organic vegetable delivery services. Understand our service agreement, user responsibilities, and business policies."
        keywords="terms and conditions, service agreement, usage policy, legal terms, NaturallyGood terms, Kanpan Organic Farms terms"
        url="https://www.naturallygood.in/terms-and-conditions.php"
      />
      {/* Hero Section */}
      <motion.section 
        className="terms-hero"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <div className="terms-hero-content">
          <h1 className="terms-title">Terms and Conditions</h1>
          <p className="terms-subtitle">
            Please read these terms carefully before using our services. By accessing our platform, you agree to be bound by these terms.
          </p>
          <div className="last-updated">
            Last updated: September 15, 2025
          </div>
        </div>
      </motion.section>

      {/* Content Section */}
      <motion.div 
        className="terms-content"
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.2 }}
      >
        <div className="content-wrapper">
          {/* Table of Contents */}
          <div className="table-of-contents">
            <h3>Quick Navigation</h3>
            <ul>
              <li><a href="#general">General</a></li>
              <li><a href="#definitions">Defined Terms</a></li>
              <li><a href="#acceptance">Acceptance of Terms</a></li>
              <li><a href="#registration">Registration and Use</a></li>
              <li><a href="#material-submission">Material Submission</a></li>
              <li><a href="#payment">Payment</a></li>
              <li><a href="#deliveries">Deliveries & Refunds</a></li>
              <li><a href="#information-use">Use of Information</a></li>
              <li><a href="#restrictions">Restrictions</a></li>
              <li><a href="#user-undertakings">User Undertakings</a></li>
              <li><a href="#disclaimers">Disclaimers</a></li>
              <li><a href="#liability">No Liability</a></li>
              <li><a href="#indemnification">Indemnification</a></li>
              <li><a href="#termination">Termination</a></li>
              <li><a href="#miscellaneous">Miscellaneous</a></li>
            </ul>
          </div>

          {/* Main Content */}
          <div className="main-content">
            
            {/* General */}
            <section id="general" className="content-section">
              <div className="section-header">
                <FileText size={24} color="#78B826" />
                <h2>I. General</h2>
              </div>
              <p>
                This website <a href="https://www.NaturallyGood.in" target="_blank" rel="noopener noreferrer">www.NaturallyGood.in</a>, 
                is owned, hosted and operated by <strong>Kanpan Organic Farms Private Limited (KOFPL)</strong>.
              </p>
              <p>
                Naturally Good is an integrated farm, fresh produce and farming venture, involving (i) subscriptions to fresh, 
                healthy and organically grown vegetables and fruits, from Naturally Good on farms designated for Users, and 
                (ii) sale of other products grown/produced by Naturally Good or sourced through partner farms/ventures, 
                wherein users can avail the products and services offered by Naturally Good.
              </p>
              <div className="important-notice">
                <AlertTriangle size={20} color="#f59e0b" />
                <p>
                  Please read this document carefully. These terms, regulating the access to Naturally Good and use of the 
                  Products & Services, constitute a legally binding agreement between Naturally Good and the User.
                </p>
              </div>
              <p>
                This document is an electronic record in terms of the Information Technology Act and the rules enacted thereunder. 
                This electronic record is generated by a computer system and does not require any physical or digital signatures.
              </p>
              <p>
                Information available on Naturally Good should not be regarded as a substitute for professional, legal, 
                financial or any other category of advice. Users should conduct their own due diligence and obtain 
                professional advice prior to consummation of any transactions.
              </p>
            </section>

            {/* Defined Terms */}
            <section id="definitions" className="content-section">
              <div className="section-header">
                <User size={24} color="#78B826" />
                <h2>II. Defined Terms</h2>
              </div>
              <p>Unless otherwise specified, the capitalized words shall have the meanings as defined herein below:</p>
              
              <div className="definitions-grid">
                <div className="definition-item">
                  <h4>Information Technology Act</h4>
                  <p>means the Information Technology Act, 2000, as amended.</p>
                </div>
                <div className="definition-item">
                  <h4>Kanpan Organic Farms Pvt Ltd</h4>
                  <p>a private limited company incorporated in India</p>
                </div>
                <div className="definition-item">
                  <h4>Person</h4>
                  <p>means any natural person, company, corporation, partnership or any other entity that is a legal person under law.</p>
                </div>
                <div className="definition-item">
                  <h4>Subscriber/Member</h4>
                  <p>means any Person who has subscribed to the Services (whether on a paid or free basis) or purchased any item from Naturally Good or has logged into Naturally Good website or app</p>
                </div>
                <div className="definition-item">
                  <h4>Terms</h4>
                  <p>means these terms and conditions and any policy/terms so mentioned by terms of reference.</p>
                </div>
                <div className="definition-item">
                  <h4>User or You</h4>
                  <p>means any Person who accesses Naturally Good or avails the Products or Services or makes a purchase or accesses Naturally Good for the purpose of viewing, browsing, publishing, sharing, transacting, displaying or uploading information or views and includes Subscribers, browsers / visitors and advertisers.</p>
                </div>
              </div>
            </section>

            {/* Acceptance of Terms */}
            <section id="acceptance" className="content-section">
              <div className="section-header">
                <CheckCircle size={24} color="#78B826" />
                <h2>III. Acceptance of Terms</h2>
              </div>
              <p>
                The use of Naturally Good is solely governed by these Terms. By accessing or using Naturally Good or availing 
                any of the Services, You agree to be bound by these Terms. If You do not agree with any of the Terms, You should 
                not access or use Naturally Good.
              </p>
              <p>
                If You have any questions, queries or concerns about these Terms, please contact us at 
                <a href="mailto:EatFresh@Naturallygood.in"> EatFresh@Naturallygood.in</a>
              </p>
              <p>
                By impliedly or expressly accepting these Terms, You also accept and agree to be bound by our Privacy Policy 
                available at <a href="/privacy-policy.php">www.naturallygood.in</a>, which may be amended from time to time.
              </p>
              <p>
                In addition to the Terms, You will be subject to the rules, guidelines, policies, terms and conditions applicable 
                to any Service or for accessing Naturally Good, that are provided on Naturally Good, which shall be deemed to be 
                incorporated into the Terms and shall be considered as part of the Terms.
              </p>
            </section>

            {/* Registration and Use */}
            <section id="registration" className="content-section">
              <div className="section-header">
                <UserPlus size={24} color="#78B826" />
                <h2>IV. Registration and Use</h2>
              </div>
              
              <div className="subsection-card">
                <h4>Eligibility Requirements</h4>
                <p>
                  The membership of Naturally Good is available only to those who are above the age of 18 (eighteen) years, 
                  excluding such persons who are incompetent to contract under the Indian Contract Act, 1872, which include 
                  inter alia persons of unsound mind and persons who are disqualified from contracting by any law to which they are subject to.
                </p>
                <p>
                  If You are a minor and wish to browse/use Naturally Good, you may do so through your legal guardian, however, 
                  Naturally Good reserves the right to terminate your account upon obtaining any information/knowledge of You being 
                  a minor and using the membership of Naturally Good.
                </p>
              </div>

              <div className="subsection-card">
                <h4>Account Security</h4>
                <p>
                  You are solely responsible for protecting the confidentiality of your username and password and any activity 
                  under the account will be deemed to have been done by You. You agree to:
                </p>
                <ul>
                  <li>provide true, accurate, current and complete information about yourself (User Information) as prompted by the sign-up process</li>
                  <li>maintain and promptly update the User Information provided during sign up to keep it true, accurate, current, and complete</li>
                </ul>
                <p>
                  Please notify Naturally Good immediately, at <a href="mailto:EatFresh@Naturallygood.in">EatFresh@Naturallygood.in</a>, 
                  in the event of any compromise or unauthorized use of your account.
                </p>
              </div>

              <div className="subsection-card">
                <h4>Communication Consent</h4>
                <p>
                  By accessing Naturally Good or availing the Services and providing us with the User Information, You agree that:
                </p>
                <ul>
                  <li>we can send you communications about Naturally Good or the Services</li>
                  <li>You may be contacted by us or our service providers, whether by phone, mobile phone, text (SMS), email, postal mail or otherwise</li>
                </ul>
              </div>
            </section>

            {/* Material Submission */}
            <section id="material-submission" className="content-section">
              <div className="section-header">
                <Info size={24} color="#78B826" />
                <h2>V. Submission and Administration of Any Material by Users</h2>
              </div>
              <p>
                You agree not to submit any material, including but not limited to links, photographs, videos etc, financial, 
                contact or other information on Naturally Good unless You have acquired or received all necessary rights and 
                authorizations from the owner/power of attorney holder of such material.
              </p>
              <p>
                Naturally Good shall have the sole authority to choose the manner in which any material will be searched, 
                displayed, accessed, downloaded, copied and otherwise used on Naturally Good and Naturally Good shall have 
                the right to modify the material in the exercise of its rights under these Terms.
              </p>
              <p>
                Naturally Good reserves the right to remove all or any part of material posted on Naturally Good without notice. 
                Naturally Good accepts no responsibility for checking/verifying the accuracy of material or data files submitted 
                by the User on Naturally Good.
              </p>
            </section>

            {/* Payment */}
            <section id="payment" className="content-section">
              <div className="section-header">
                <CreditCard size={24} color="#78B826" />
                <h2>VI. Payment</h2>
              </div>
              
              <div className="payment-info">
                <h4>Payment Requirements</h4>
                <p>
                  Users are required to pay the applicable charges for the Services. The details of the charges are clearly 
                  set out on Naturally Good. You may communicate with us at 
                  <a href="mailto:EatFresh@Naturallygood.in"> EatFresh@Naturallygood.in</a> to get more information in this regard.
                </p>
              </div>

              <div className="payment-types">
                <div className="payment-type-card">
                  <h4>Subscription Payments</h4>
                  <p>
                    Any payments for subscriptions to different subscription packages offered by Naturally Good, will be treated 
                    as an advance paid toward supply of fresh, healthy and organically grown vegetables and fruits, from Naturally Good.
                  </p>
                  <p>
                    All services associated with the aforementioned supply of fresh produce, such as access to the Naturally Good 
                    App and website, farm visits, workshops (unless paid for), deliveries (if a part of the model subscribed to), 
                    training etc., will be treated as free of cost add-ons to the primary services/produce.
                  </p>
                </div>
                
                <div className="payment-type-card">
                  <h4>Other Products/Services</h4>
                  <p>
                    Any payments for other products/services listed on Naturally Good, will be billed to you directly by 
                    Naturally Good or partner service providers, against an invoice/bill of supply, as the case may be.
                  </p>
                </div>
              </div>

              <div className="important-notice">
                <AlertTriangle size={20} color="#f59e0b" />
                <p>
                  <strong>Important:</strong> You understand and undertake that any monies paid while accessing Naturally Good 
                  do not and will not constitute any type of real estate transaction. You will not have any legal or any form 
                  of rights in the land on which User farms are demarcated or on any of the Naturally Good farms.
                </p>
              </div>
            </section>

            {/* Deliveries */}
            <section id="deliveries" className="content-section">
              <div className="section-header">
                <Truck size={24} color="#78B826" />
                <h2>VII. Deliveries Schedule, Returns and Refunds</h2>
              </div>
              
              <div className="delivery-policy">
                <div className="policy-item">
                  <h4>Delivery Timeline</h4>
                  <p>All orders will be delivered within 24 to 72 hours depending upon the plan and delivery date and time slot chosen by the customer.</p>
                </div>
                
                <div className="policy-item">
                  <h4>Returns & Refunds</h4>
                  <p>
                    Due to the perishable nature of our products, customers are requested to kindly open a support ticket on 
                    NaturallyGood app or email us at <a href="mailto:EatFresh@Naturallygood.in">EatFresh@Naturallygood.in</a> 
                    a photograph of the damaged consignment within 24 hours of receipt.
                  </p>
                  <p>
                    If you are approved, then your refund will be processed, and a credit will automatically be applied to the 
                    original method of payment, within 7 working days.
                  </p>
                  <p>
                    Refund of monies paid, if any, will be at the sole discretion of Naturally Good. Any refund queries will 
                    be ascertained on a case to case basis.
                  </p>
                </div>
              </div>
            </section>

            {/* Use of Information */}
            <section id="information-use" className="content-section">
              <div className="section-header">
                <Shield size={24} color="#78B826" />
                <h2>VIII. Use of Information</h2>
              </div>
              
              <p>
                You agree to treat all information obtained from access to Naturally Good, or any of the Services and any 
                information otherwise made available to You under any Service or access to Naturally Good ("Information") 
                as proprietary to Naturally Good.
              </p>
              
              <div className="restrictions-list">
                <h4>You hereby agree and undertake:</h4>
                <ul>
                  <li>To not use any Information for further distribution, publication, public display or preparation of derivative works without prior consent</li>
                  <li>Not to reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any Information</li>
                  <li>Not to use Naturally Good in a manner that violates any laws or regulations</li>
                  <li>Not to stalk, harass, or harm another Person</li>
                  <li>Not to impersonate any Person or misrepresent your affiliation</li>
                  <li>Not to interfere with or disrupt Naturally Good or servers or networks connected to Naturally Good</li>
                </ul>
              </div>
            </section>

            {/* Restrictions */}
            <section id="restrictions" className="content-section">
              <div className="section-header">
                <Ban size={24} color="#dc2626" />
                <h2>IX. Restrictions and Prohibitions</h2>
              </div>
              
              <div className="prohibited-actions">
                <h4>You expressly agree not to:</h4>
                <div className="prohibition-grid">
                  <div className="prohibition-item">
                    <XCircle size={20} color="#dc2626" />
                    <p>Access Naturally Good in any manner that impairs its functioning</p>
                  </div>
                  <div className="prohibition-item">
                    <XCircle size={20} color="#dc2626" />
                    <p>Access any data you are not authorized to access</p>
                  </div>
                  <div className="prohibition-item">
                    <XCircle size={20} color="#dc2626" />
                    <p>Attempt to breach security or authentication measures</p>
                  </div>
                  <div className="prohibition-item">
                    <XCircle size={20} color="#dc2626" />
                    <p>Interfere with access to any other User</p>
                  </div>
                  <div className="prohibition-item">
                    <XCircle size={20} color="#dc2626" />
                    <p>Copy, distribute, or modify any material without permission</p>
                  </div>
                  <div className="prohibition-item">
                    <XCircle size={20} color="#dc2626" />
                    <p>Remove copyright, trademark or other intellectual property notices</p>
                  </div>
                </div>
              </div>

              <div className="content-restrictions">
                <h4>Prohibited Content</h4>
                <p>You are prohibited from hosting, displaying, uploading or sharing any information that:</p>
                <ul>
                  <li>belongs to another person and to which you do not have any right</li>
                  <li>is harmful, harassing, blasphemous, defamatory, obscene, pornographic, or libelous</li>
                  <li>harms minors in any way</li>
                  <li>infringes any patent, trademark, copyright or other proprietary rights</li>
                  <li>violates any law for the time being in force</li>
                  <li>deceives or misleads about the origin of messages</li>
                  <li>contains software viruses or malicious code</li>
                  <li>threatens the unity, integrity, defence, security or sovereignty of India</li>
                </ul>
              </div>
            </section>

            {/* Contact */}
            <section id="contact" className="content-section">
              <div className="section-header">
                <MessageSquare size={24} color="#78B826" />
                <h2>Complaints and Grievance Redressal</h2>
              </div>
              <div className="contact-card">
                <h4>Need Help or Have Concerns?</h4>
                <p>Any complaints, abuse or concerns with regards to content and or comment or breach of these Terms shall be immediately informed to the designated Grievance Officer:</p>
                <div className="contact-info">
                  <div className="contact-item">
                    <span className="contact-label">Position:</span>
                    <span>Head – Customer Support</span>
                  </div>
                  <div className="contact-item">
                    <span className="contact-label">Email:</span>
                    <a href="mailto:Admin@Naturallygood.in">Admin@Naturallygood.in</a>
                  </div>
                  <div className="contact-item">
                    <span className="contact-label">Company:</span>
                    <span>Kanpan Organic Farms Private Limited</span>
                  </div>
                  <div className="contact-item">
                    <span className="contact-label">Website:</span>
                    <a href="https://www.naturallygood.in/" target="_blank" rel="noopener noreferrer">www.naturallygood.in</a>
                  </div>
                </div>
              </div>
            </section>

          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default TermsConditions;